apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-mysql
spec:
  selector:
    matchLabels:
      app: Studentapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: student-mysql
    spec:
      containers:
       - name: satish736
         image: satish736/mysql:1.0
#      image: acmeorg/consul:latest
         imagePullPolicy: Always
         command: [ "echo", "SUCCESS" ]
      imagePullSecrets:
        - name: satish736
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: student-mysql
        volumeMounts:
        - name: mysql-persistent-storage-dev
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-dev
        persistentVolumeClaim:
          claimName: student-pvc
