apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-mysql
spec:
  selector:
    matchLabels:
      app: Studentapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: Studentapp
    spec:
      containers:
      - image: satish736/mysql:1.0
        name: student-mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: student-mysql
        volumeMounts:
        - name: mysql-persistent-storage-dev
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-dev
        persistentVolumeClaim:
          claimName: student-pvc
