apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-student
spec:
  type: NodePort
  selector:
    app: Studentapp
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227
