apiVersion: apps/v1                          
kind: Deployment
metadata:
  name: tomcat-deployment-student
spec:
  selector:
    matchLabels:
      app: Studentapp
  template:
    metadata:
      labels:
        app: tomcat-deployment-student
    spec:
      containers:
        - name: tomcat-container-student
          image: satish736/tomcat-student:1.0
          ports:
            - containerPort: 8080
